#!/bin/bash

# Install git if not already installed
git --version 2>&1 >/dev/null
GIT_IS_AVAILABLE=$?

if [ ! $GIT_IS_AVAILABLE -eq 0 ]; then
  echo -e "\033[92mInstalling git\033[0m"
  sudo apt install -y git
fi

# Clone repo
echo -e "\033[92mCloning repo\033[0m"
cd ~ && git clone https://gitlab.com/yozz/dotfiles.git

# Run bootstrap
~/dotfiles/bootstrap

# Delete install script
rm -rf ~/dotfiles-installer-master
